-- Game servers authorised to submit runs. A row here is an operational fact,
-- not an identity claim: the bearer token is what authenticates a submission.
CREATE TABLE game_servers (
    id           TEXT PRIMARY KEY,
    region       TEXT NOT NULL DEFAULT 'unknown',
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- One attempt. The id is generated by the game server so a retried submission
-- after a network failure cannot post the same run twice.
CREATE TABLE runs (
    id                 TEXT PRIMARY KEY,
    boss               TEXT NOT NULL,
    outcome            TEXT NOT NULL,
    duration_ms        BIGINT NOT NULL,
    content_hash       TEXT NOT NULL,
    engine             TEXT NOT NULL,
    authority          TEXT NOT NULL,

    -- A fingerprint of the whole submission. Comparing a few columns let a
    -- different run reusing an id pass as a retry. No default: a run without one
    -- cannot exist, so there is no "unknown digest" case to reason about.
    submission_digest  TEXT NOT NULL,

    -- The backend's conclusion, never the submitter's claim.
    rankable           BOOLEAN NOT NULL,
    unrankable_reason  TEXT,

    worst_overreach_cm BIGINT NOT NULL,
    game_server        TEXT NOT NULL,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE run_players (
    run_id         TEXT NOT NULL REFERENCES runs(id) ON DELETE CASCADE,

    -- How this slot was ADDRESSED during the fight. Unique within a run and
    -- meaningless outside it: a fresh random integer every connection.
    peer           BIGINT NOT NULL,

    -- Who the slot belonged to, and how much the server actually knew about
    -- that. 'anonymous' means the value was accepted unchecked, because there
    -- was nothing to check it against; it identifies an install, not a person.
    -- A verified provenance replaces the value here without moving the column.
    player_id      TEXT NOT NULL,
    display_name   TEXT NOT NULL,
    identity       TEXT NOT NULL,

    damage_done    BIGINT NOT NULL,
    healing_done   BIGINT NOT NULL,
    damage_taken   BIGINT NOT NULL,
    overreach_cm   BIGINT NOT NULL,
    PRIMARY KEY (run_id, peer)
);

-- The ladder query: fastest ranked clears of one boss on one balance patch.
CREATE INDEX runs_ladder_idx
    ON runs (boss, content_hash, duration_ms)
    WHERE rankable;

CREATE INDEX runs_created_at_idx ON runs (created_at DESC);

-- "Every run this player was in", which is the question the peer id could never
-- answer.
CREATE INDEX run_players_identity_idx ON run_players (identity, player_id);
